spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop # docker config
    # ddl-auto: validate # helios config

server:
  port: 8080
