spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # docker config
    # url: jdbc:postgresql://localhost:5432/studs # helios config
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      # ddl-auto: validate # helios config
      ddl-auto: create-drop # docker config

server:
  port: 8080
