spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate

server:
  port: 8080
