spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop

facebook:
  client:
    clientId: clientId
    clientSecret: clientSecret # FIXME do not forget to remove it before new commit
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: PASSWORD
    keyStoreType: PKCS12
    keyAlias: tomcat
