package org.robogit.dto

import org.robogit.domain.*
import java.util.*

class MegaInformationDto(var id: Int?,
                         var type: Type?,
                         var model: String?,
                         var name: String?,
                         var image: String?,
                         var price: Float?,
                         var creationDate: Date?,
                         var provider: String?,
                         var description: String?,
                         var amount: Int?,
                         var ram: Int?,
                         var minVoltage: Float?,
                         var maxVoltage: Float?,
                         var analogInputs: Int?,
                         var material: String?,
                         var power: Float?,
                         var freq: Float?,
                         var flashmemory: Int?) {


    constructor(information: Information, controller: Controller): this(information.id,
                                                                        information.type,
                                                                        information.model,
                                                                        information.name,
                                                                        information.image,
                                                                        information.price,
                                                                        information.creationDate,
                                                                        information.provider,
                                                                        information.description,
                                                                        information.amount,
                                                                        controller.ram,
                                                                        controller.minVoltage,
                                                                        controller.maxVoltage,
                                                                        controller.analogInputs,
                                                                        null,
                                                                        null,
                                                                        null,
                                                                        null)


    constructor(information: Information, mechanicDetail: MechanicDetail): this(information.id,
                                                                                information.type,
                                                                                information.model,
                                                                                information.name,
                                                                                information.image,
                                                                                information.price,
                                                                                information.creationDate,
                                                                                information.provider,
                                                                                information.description,
                                                                                information.amount,
                                                                                null,
                                                                                null,
                                                                                null,
                                                                                null,
                                                                                mechanicDetail.material,
                                                                                null,
                                                                                null,
                                                                                null)


    constructor(information: Information, motor: Motor) :  this(information.id,
                                                                information.type,
                                                                information.model,
                                                                information.name,
                                                                information.image,
                                                                information.price,
                                                                information.creationDate,
                                                                information.provider,
                                                                information.description,
                                                                information.amount,
                                                                null,
                                                                motor.minVoltage,
                                                                motor.maxVoltage,
                                                                null,
                                                                null,
                                                                motor.power,
                                                                null,
                                                                null)


    constructor(information: Information, sensor: Sensor): this(information.id,
                                                                information.type,
                                                                information.model,
                                                                information.name,
                                                                information.image,
                                                                information.price,
                                                                information.creationDate,
                                                                information.provider,
                                                                information.description,
                                                                information.amount,
                                                                null,
                                                                sensor.minVoltage,
                                                                sensor.maxVoltage,
                                                                null,
                                                                null,
                                                                null,
                                                                null,
                                                                null)


    constructor(information: Information, platform: Platform): this(information.id,
                                                                    information.type,
                                                                    information.model,
                                                                    information.name,
                                                                    information.image,
                                                                    information.price,
                                                                    information.creationDate,
                                                                    information.provider,
                                                                    information.description,
                                                                    information.amount,
                                                                    platform.ram,
                                                                    platform.minVoltage,
                                                                    platform.maxVoltage,
                                                                    platform.analogInputs,
                                                                    null,
                                                                    null,
                                                                    platform.freq,
                                                                    platform.flashmemory)


    constructor(information: Information): this(information.id,
                                                information.type,
                                                information.model,
                                                information.name,
                                                information.image,
                                                information.price,
                                                information.creationDate,
                                                information.provider,
                                                information.description,
                                                information.amount,
                                                null,
                                                null,
                                                null,
                                                null,
                                                null,
                                                null,
                                                null,
                                                null)
}